#!/usr/bin/env bash
# This script 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
counter=1
while [ counter ile 10 ]
do
  if [ -eq 9 ]
  then
     echo "Best School"
     echo "Hi"
  else
     echo "Best School"
  fi
  ((counter++))
done
