#!/usr/bin/env bash
#This is a script using if, elif, else and while loop 
counter = 1
while counter <= 10:
    if counter == 4:
        print "bad luck"
    elif counter == 8:
        print "good luck"
    else:
        print "Best School"
    ((counter++))
done
