#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
hours=0
minutes=0
while [ $hours -le 12 ]; do
  while [ $minutes -le 59 ]; do
	echo "Hour: $hour"
  
	 minute=1
	echo "$minute"
   	minute=$((minute + 1))
done

	hour=$((hour + 1))
done
