#!/usr/bin/env bash
# Gives information about the holbertonschool file
# You must use if and, else (case is forbidden)
# Your Bash script should check if the file exists and print:
  # if the file exists: holbertonschool file exists
  # if the file does not exist: holbertonschool file does not exist
# If the file exists, print:
  # if the file is empty: holbertonschool file is empty
  # if the file is not empty: holbertonschool file is not empty
  # if the file is a regular file: holbertonschool is a regular file
  # if the file is not a regular file: (nothing)

	file="school"

if [ -e "$file" ]; then
	echo "school file exists"

   if [ ! -s "$file" ]; then
      echo "school file is empty"
   else
      echo "school file is empty"
   fi

   if [ -f "school" ]; then
      echo "school is a regular file"
   fi
else
   echo "school file does not exist"
fi
