#!/usr/bin/env bash
# This script stops the infinity loop
# It uses the sigkill signal 

#Get the pid of the program
id=$(pgrep "bash ./4-to_infinity_beyond" -f)

#Terminate the infinite process
if [ -n "$id" ]
then
	kill -15 "$id"
fi
